from pydantic import BaseModel
from datetime import datetime
from typing import List

class Preset(BaseModel):
    T_base: float
    A_T: float
    sigma_T: float
    drift_T_per_day: float
    S_base: float
    drift_S_per_min: float
    sigma_S: float
    waterchange_reduction: float
    waterchange_frequency_days: float
    k_evap_per_deg: float
    O2_base: float
    A_O2: float
    sigma_O2: float
    k_T_O2: float
    O2_event_prob_per_day: float
    hypoxia_min: float
    hypoxia_max: float
    O2_floor: float
    pH_base: float
    A_pH: float
    sigma_pH: float
    k_feed_acid: float
    k_O2_pH: float
    pH_recovery_on_waterchange: float
    O2_pH_threshold: float
    pH_smoothing_alpha: float
    pH_min_limit: float
    pH_max_limit: float
    Feed_base: float
    feed_spike_multiplier: float
    feed_spike_prob_per_day: float
    feed_spike_duration_min: List[float]
    feed_noise_min_factor: float
    feed_noise_max_factor: float
    feed_min_kg_min: float
    V: float
    initial_N: float
    stocking_prob_per_day: float
    stocking_min: float
    stocking_max: float
    alpha: float
    beta: float
    gamma: float
    weight_salinity: float
    kappa: float
    shock_factor: float
    O2_crit_for_shock: float
    density_crit_for_shock: float
    max_mortality_rate: float
    T_opt: float
    O2_crit: float
    rho_opt: float
    salinity_optimal_min: float
    salinity_optimal_max: float
    salinity_lethal_low: float
    salinity_lethal_high: float
    sanity_temp_crit_for_ph: float
    sanity_ph_min_at_crit_temp: float
    sanity_ph_fix_noise_min: float
    sanity_ph_fix_noise_max: float
    sanity_o2_crit_for_ph: float
    sanity_ph_max_at_crit_o2: float
    sanity_density_crit_for_o2: float
    sanity_o2_max_at_crit_density: float
    sanity_o2_fix_noise_min: float
    sanity_o2_fix_noise_max: float
    sanity_salinity_max_with_wc: float
    sanity_sal_fix_noise_min: float
    sanity_sal_fix_noise_max: float
    sanity_max_mortality_ratio: float
    initial_weight_g: float
    feed_table: List[List[float]]
    target_weight_g: float
    fcr: float
    temp_min_growth: float
    temp_optimal_growth: float
    temp_max_growth: float

class SimulationPayload(BaseModel):
    days: int
    seed: int
    start_time: datetime
    tank_id: int
    preset: Preset
